### ISSUE TITLE
PHP 8.1 to 8.2 update causes error with  DateTimeRange

### ISSUE THREAD

**Issue by jhoelzl** [PandaHugMonster/php-simputils#170]
Usage of this causes an error when using PHP 8.2.12 instead PHP 8.1.9:

```php
/**
	 * @param $time_range
	 * @param null|string|int|DateTime $now_ref
	 *
	 * @return \app\components\standard\DatePeriod
	 * @noinspection PhpIncompatibleReturnTypeInspection
	 * @noinspection PhpMissingReturnTypeInspection
	 * @noinspection PhpReturnDocTypeMismatchInspection
	 */
	static function defineDateTimeRange($time_range, null|string|int|DateTime $now_ref = null) {
		$now = !is_null($now_ref)
			?ts($now_ref)
			:now();
		$now_d = $now->clone()->setTime(0, 0, 0);

		$now_m = $now_d->clone();
		$now_m->day = 1;

		$now_d->modify('+1 day'); // Pointing to the end of today

		return match (true) {

			bx(['1h', 'last1hour'])->containsValue($time_range)
			=> $now->period('-1 hour'),

			bx(['last15min'])->containsValue($time_range)
			=> $now->period('-15 minutes'),

			bx(['4h', 'last4hours'])->containsValue($time_range)
			=> $now->period('-4 hours'),

			bx(['12h', 'last12hours'])->containsValue($time_range)
			=> $now->period('-12 hours'),

			bx(['24h', 'last24hours'])->containsValue($time_range)
			=> $now->period('-24 hours'),

			bx(['today'])->containsValue($time_range)
			=> $now_d->period('-1 day'),

			bx(['yesterday'])->containsValue($time_range)
			=> $now_d->clone()->sub('1 day')
				->period('-1 day'),

			bx(['3d', 'last3days'])->containsValue($time_range)
			=> $now_d->period('-3 days'),

			bx(['7d', 'last7days'])->containsValue($time_range)
			=> $now_d->period('-7 days'),

			bx(['30d', 'last30days'])->containsValue($time_range)
			=> $now_d->period('-30 days'),

			bx(['60d', 'last60days'])->containsValue($time_range)
			=> $now_d->period('-60 days'),

			bx(['90d', 'last90days'])->containsValue($time_range)
			=> $now_d->period('-90 days'),

			bx(['120d', 'last120days'])->containsValue($time_range)
			=> $now_d->period('-120 days'),

			bx(['180d', 'last180days'])->containsValue($time_range)
			=> $now_d->period('-180 days'),

			bx(['month', 'thismonth'])->containsValue($time_range)
			=> $now_m->period('+1 month'),

			// MARK Ambiguous inclusive of current month or not?
			bx(['last1month'])->containsValue($time_range)
			=> $now_m->sub('1 month')
				->period('+1 month'),

			bx(['last2month'])->containsValue($time_range)
			=> $now_m->sub('2 month')
				->period('+1 month'),

			bx(['last3month'])->containsValue($time_range)
			=> $now_m->sub('3 month')
				->period('+1 month'),

			bx(['last4month'])->containsValue($time_range)
			=> $now_m->sub('4 month')
				->period('+1 month'),

			bx(['last5month'])->containsValue($time_range)
			=> $now_m->sub('5 month')
				->period('+1 month'),

			bx(['2m', 'last2months'])->containsValue($time_range)
			=> $now_m->add('1 month')
				->period('-2 month'),

			bx(['3m', 'last3months'])->containsValue($time_range)
			=> $now_m->add('1 month')
				->period('-3 month'),

			bx(['6m', 'last6months'])->containsValue($time_range)
			=> $now_m->add('1 month')
				->period('-6 month'),

			bx(['9m', 'last9months'])->containsValue($time_range)
			=> $now_m->add('1 month')
				->period('-9 month'),

			bx(['12m', 'last12months', '1y'])->containsValue($time_range)
			=> $now_m->add('1 month')
				->period('-12 month'),

			bx(['2y'])->containsValue($time_range)
			=> $now_m->add('1 month')
				->period('-2 years'),

			bx(['3y'])->containsValue($time_range)
			=> $now_m->add('1 month')
				->period('-3 years'),

			bx(['5y'])->containsValue($time_range)
			=> $now_m->add('1 month')
				->period('-5 years'),

//			bx(['all'])->containsValue($time_range)
//			=> $now_m->add('1 month')
//				->period(0),

			default => $now_m->add('1 month')
				->period(0),
		};
	}
```

with for example values
```php
$time_range = "all";
$time_range = "last24hours";
```

> NOTICE: PHP message: PHP Fatal error:  Uncaught spaf\simputils\exceptions\PropertyDoesNotExist: No such property from_string in /app/vendor/spaf/simputils/src/traits/PropertiesTrait.php:269
Stack trace:
#0 /app/vendor/spaf/simputils/src/traits/PropertiesTrait.php(95): spaf\simputils\generic\fixups\FixUpDateInterval->_simpUtilsPrepareProperty('from_string', 'set', false)
#1 /app/vendor/spaf/simputils/src/traits/MetaMagic.php(489): spaf\simputils\generic\fixups\FixUpDateInterval->__set('from_string', false)
#2 /app/vendor/spaf/simputils/src/traits/MetaMagic.php(604): spaf\simputils\generic\fixups\FixUpDateInterval->___setup(Array)
#3 /app/vendor/spaf/simputils/src/PHP.php(252): spaf\simputils\generic\fixups\FixUpDateInterval::_metaMagic(Object(spaf\simputils\models\DateInterval), '___setup', Array)
#4 /app/vendor/spaf/simputils/src/traits/MetaMagic.php(425): spaf\simputils\PHP::metaMagicSpell(Object(spaf\simputils\models\DateInterval), '___setup', Array)
#5 /app/vendor/spaf/simputils/src/models/DateTime.php(335): spaf\simputils\generic\fixups\FixUpDateInterval::expandFrom(Object(DateInterval), Object(spaf\simputils\models\DateInterval))
#6 /app/vendor/spaf/simputils/src/models/DateTime.php(396): spaf\simputils\models\DateTime->diff(Object(app\components\standard\DateTime))
#7 /app/components/standard/DateTime.php(33): spaf\simputils\models\DateTime->period('-24 hours', NULL, true)
#8 /app/helpers/ChartHelper.php(226): app\components\standard\DateTime->period('-24 hours')
#9 /app/web/get_history.php(77): app\helpers\ChartHelper::defineDateTimeRange('last24hours')
#10 {main}
  thrown in /app/vendor/spaf/simputils/src/traits/PropertiesTrait.php on line 269

**Comment by PandaHugMonster** [comment]
@jhoelzl  Thank you for the ticket. Will investigate and fix it ASAP!

**Comment by PandaHugMonster** [comment]
@jhoelzl Patch with fixes released, please upgrade your installation.
